### PR TITLE
🚀 Implemented `onStartFailed` call back in `shelf_run.dart`.

### LINKED ISSUE #27: onStartFailed CallBack!
@felixblaschke 
```dart

void main(List<String> args) {
  try {
    initConfig(args.first);
    shelfRun(init, defaultBindAddress: host,
        defaultBindPort: port,
        onStarted: (address, port) =>
            print('[STARTED] Listening at http://$address:$port'));
  }
  on SocketException catch(e){
    print("[FAILED] Cannot start the server!");
    print(e);
  }
}
```
Hi!
I am writing a chat program,
I come across this problem that
There is a `onStarted` callBack but I can't find a way to know implicitly if the server has failed to start!
Not even `try-catch` block can handle it cause it seems that server launch is a async operation.

Likewise `onStarted`, there should be a `onStartFailed` callback.

### PR DESCRIPTION
**Pull request by omegaui**
@felixblaschke 
This Fixes #27 .
Hey There!
This commit adds support for `onStartFailed` call back in `shelfRun()` function. This enables us to know if the server was crashed due to any `SocketException` that occurs during Initialization. Since, `shelfRun` process is an asynchronized  operation, it was not externally possible to handle the exception that occurs during initializatiion. But this commit, enables you to handle it via the `onStartFailed` call back! Heres, an example call:
```dart
void main(){
    shelfRun(init, onStartFailed: (e) => print("An error occured during server initilization"));
}
```

### CODE REVIEW

**Comment by felixblaschke** [comment]
Thank you for you contribution. I will guide you through the code review 👍

File: lib/src/shelf_run.dart [hunk 1]
```diff
@@ -38,26 +40,46 @@ Future<ShelfRunContext> shelfRun(
...
+          defaultBindPort: defaultBindPort,
+          defaultBindAddress: defaultBindAddress,
+          defaultShared: defaultShared,
+          securityContext: securityContext,
+          onStarted: onStarted,
+        );
+        context._server = server;
+      }
+      on SocketException catch(e){
+        if(onStartFailed != null) {
```
Comment (felixblaschke) [inline lib/src/shelf_run.dart:55]: This code part seems to double. What about simplifying this by adding something like
```
onStartFailed ?= print;
```
some lines above (e.g. line 40)

File: lib/src/shelf_run.dart [hunk 2]
```diff
@@ -38,26 +40,46 @@ Future<ShelfRunContext> shelfRun(
...
-      init,
-      defaultBindPort: defaultBindPort,
-      defaultBindAddress: defaultBindAddress,
-      defaultShared: defaultShared,
-      securityContext: securityContext,
-      onStarted: onStarted,
-    );
+    }
+    on SocketException catch(e){
+      if(onStartFailed != null) {
```
Comment (felixblaschke) [inline lib/src/shelf_run.dart:76]: this is the code part which doubles. see https://github.com/felixblaschke/shelf_plus/pull/28/files#r1113107271

File: lib/src/shelf_run.dart [hunk 3]
```diff
@@ -38,26 +40,46 @@ Future<ShelfRunContext> shelfRun(
...
+        onStartFailed.call(e);
+      }
+      else{
```
Comment (felixblaschke) [inline lib/src/shelf_run.dart:79]: this code needs to dart formatter to run 🦖 

e.g. `else{` => `else {`

File: lib/src/shelf_run.dart [hunk 4]
```diff
@@ -38,26 +40,46 @@ Future<ShelfRunContext> shelfRun(
...
-    await _createServer(
-      init,
-      defaultBindPort: defaultBindPort,
-      defaultBindAddress: defaultBindAddress,
-      defaultShared: defaultShared,
-      securityContext: securityContext,
-      onStarted: onStarted,
-    );
+    }
+    on SocketException catch(e){
```
Comment (felixblaschke) [inline lib/src/shelf_run.dart:75]: the new ability (when e.g. an exception occurs while starting the server => custom action trigger) should reflect within a unit test (`test/`)

File: lib/src/shelf_run.dart [hunk 5]
```diff
@@ -38,26 +40,46 @@ Future<ShelfRunContext> shelfRun(
...
+          init,
+          defaultBindPort: defaultBindPort,
+          defaultBindAddress: defaultBindAddress,
+          defaultShared: defaultShared,
+          securityContext: securityContext,
+          onStarted: onStarted,
+        );
+        context._server = server;
+      }
+      on SocketException catch(e){
```
Comment (felixblaschke) [inline lib/src/shelf_run.dart:54]: Do you think it's good to raise any exception, to be not only limited to `SocketException`? What you think?

**Comment by omegaui** [comment]
@felixblaschke 
Have a look now!

**Comment by felixblaschke** [comment]
This looks really cool. Awesome work. I'll make a release of it later. 🥳
